
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: reverseproxy
#   labels:
#     app: reverseproxy
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: reverseproxy
#   template:
#     metadata:
#       labels:
#         app: reverseproxy
#     spec:
#       containers:
#       - name: reverseproxy
#         image: trhthang/reverseproxy:v1
#         ports:
#           - containerPort: 80

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udagram-reverseproxy
  name: udagram-reverseproxy
spec:
  replicas: 2
  selector:
    matchLabels:
      service: udagram-reverseproxy
  template:
    metadata:
      labels:
        service: udagram-reverseproxy
    spec:
      containers:
        - image: trhthang/reverseproxy:v1
          name: udagram-reverseproxy
          imagePullPolicy: Always
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "2042Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
      restartPolicy: Always